# PlatformIO pre-build script: stamps the firmware with its git version and
# build time, reported by /api/health ("firmware").
#
# Writes a generated header instead of adding -D flags: a define whose value
# changes on every build (the time) would recompile the whole project and
# its libraries each time, while only routes_health.cpp includes this.
#
#   FIRMWARE_VERSION     `git describe --always --dirty --tags`
#                        (e.g. "da45cb1-dirty"), "unknown" outside git
#   FIRMWARE_BUILD_TIME  UTC, ISO 8601
import os
import subprocess
from datetime import datetime, timezone

Import("env")  # noqa: F821 -- provided by PlatformIO


def git_version():
    try:
        return subprocess.check_output(
            ["git", "describe", "--always", "--dirty", "--tags"],
            cwd=env["PROJECT_DIR"],  # noqa: F821
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(out_dir, exist_ok=True)
build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
with open(os.path.join(out_dir, "firmware_version.h"), "w") as header:
    header.write(
        "#pragma once\n"
        "// Generated by scripts/firmware_version.py -- do not edit.\n"
        f'#define FIRMWARE_VERSION "{git_version()}"\n'
        f'#define FIRMWARE_BUILD_TIME "{build_time}"\n'
    )

env.Append(CPPPATH=[out_dir])  # noqa: F821
