#include "routes_health.h"

#include <WiFi.h>
#include <esp_system.h>

#include "config.h"
#include "firmware_version.h" // generated by scripts/firmware_version.py
#include "json_codec.h"
#include "modbus_task.h"
#include "ws_stream.h"

namespace {

// Why the chip last started. Anything but power_on / software after a
// deploy points at a problem: panic = crash, brownout = supply voltage
// sagged (weak USB port or supply), *_watchdog = something hung.
const char *resetReasonName(esp_reset_reason_t reason) {
  switch (reason) {
    case ESP_RST_POWERON: return "power_on";
    case ESP_RST_EXT: return "external_pin";
    case ESP_RST_SW: return "software";
    case ESP_RST_PANIC: return "panic";
    case ESP_RST_INT_WDT: return "interrupt_watchdog";
    case ESP_RST_TASK_WDT: return "task_watchdog";
    case ESP_RST_WDT: return "other_watchdog";
    case ESP_RST_DEEPSLEEP: return "deep_sleep";
    case ESP_RST_BROWNOUT: return "brownout";
    case ESP_RST_SDIO: return "sdio";
    default: return "unknown";
  }
}

} // namespace

void registerHealthRoutes(AsyncWebServer &server) {
  server.on("/api/health", HTTP_GET, [](AsyncWebServerRequest *request) {
    JsonDocument doc;
    doc["uptimeMs"] = millis();
    doc["freeHeap"] = ESP.getFreeHeap();
    doc["wifiRssi"] = WiFi.RSSI();
    doc["wifiIp"] = WiFi.localIP().toString();
    doc["defaultSlave"] = DEFAULT_SLAVE_ID;
    doc["resetReason"] = resetReasonName(esp_reset_reason());

    // wifiRssi / wifiIp above stay for existing clients.
    JsonObject wifi = doc["wifi"].to<JsonObject>();
    wifi["ssid"] = WiFi.SSID();
    wifi["rssi"] = WiFi.RSSI();
    wifi["ip"] = WiFi.localIP().toString();
    wifi["hostname"] = String(MDNS_HOSTNAME) + ".local";
    wifi["mac"] = WiFi.macAddress();
    wifi["channel"] = WiFi.channel();

    JsonObject firmware = doc["firmware"].to<JsonObject>();
    firmware["version"] = FIRMWARE_VERSION;
    firmware["buildTime"] = FIRMWARE_BUILD_TIME;
    firmware["arduinoCore"] = String(ESP_ARDUINO_VERSION_MAJOR) + "." + ESP_ARDUINO_VERSION_MINOR +
                              "." + ESP_ARDUINO_VERSION_PATCH;
    firmware["idf"] = ESP.getSdkVersion();
    firmware["chip"] = ESP.getChipModel();

    ModbusStats stats = getModbusStats();
    JsonObject modbus = doc["modbus"].to<JsonObject>();
    modbus["okCount"] = stats.okCount;
    modbus["errorCount"] = stats.errorCount;
    if (stats.anyAttempt) {
      modbus["lastResult"] = modbusResultName(stats.lastResult);
      modbus["lastSlave"] = stats.lastSlave;
      modbus["lastAttemptAt"] = stats.lastAttemptAt;
    } else {
      modbus["lastResult"] = "NoRequestYet";
      modbus["lastSlave"] = nullptr;
      modbus["lastAttemptAt"] = nullptr;
    }
    if (stats.lastSuccessAt != 0) {
      modbus["lastSuccessAt"] = stats.lastSuccessAt;
    } else {
      modbus["lastSuccessAt"] = nullptr;
    }
    modbus["cacheHits"] = stats.cacheHits;
    // Serial settings in use: the first thing to compare with the slave's
    // when requests time out.
    JsonObject modbusConfig = modbus["config"].to<JsonObject>();
    modbusConfig["baud"] = MODBUS_BAUD;
    modbusConfig["format"] = MODBUS_SERIAL_FORMAT;
    modbusConfig["responseTimeoutMs"] = MODBUS_RESPONSE_TIMEOUT_MS;
    modbusConfig["defaultSlave"] = DEFAULT_SLAVE_ID;

    JsonObject stream = doc["stream"].to<JsonObject>();
    stream["clients"] = wsClientCount();
    stream["subscriptions"] = stats.subscriptions;
    stream["pollBlocks"] = stats.pollBlocks;
    stream["busLoadPct"] = roundf(stats.busLoad * 1000) / 10; // one decimal
    // A slave answered the latest request -- data or a Modbus exception
    // (0x01-0x04) both prove the RS-485 link works. Without WebSocket
    // subscriptions nothing is polled, so it then reflects the last API call.
    doc["modbusLinkUp"] = stats.anyAttempt && stats.lastResult <= 0x04;

    AsyncResponseStream *response = request->beginResponseStream(JSON_CONTENT_TYPE);
    serializeJson(doc, *response);
    request->send(response);
  });
}
